### ISSUE TITLE
Subassets link is broken

### ISSUE THREAD

**Issue by deweller** [CounterpartyXCP/Documentation#127] opened 2017-05-02 13:54 UTC
The link at https://counterparty.io/docs/api/#subassets that is pointing to protocol_specification.md is broken.

The docs point to https://counterparty.io/Developers/protocol_specification.md#assets but that's 404

**Comment by unsystemizer** [comment] 2017-05-02 14:39
https://github.com/CounterpartyXCP/Documentation/blob/master/Developers/protocol_specification.md#subassets is alive, but I don't know how those links and macros that convert them work

**Comment by eliyastein** [comment] 2017-05-12 17:34
That's not the only broken link. It looks like every link pointing to Developers/protocol_specification.md is broken - it looks like it should be pointing to docs/api - but that appears to be behind what's on github. This whole thing appears to need an overhaul.

**Comment by unsystemizer** [comment] 2017-05-14 06:05
It's probably just something in the processor script that syncs the docs to the Web site. 
@robby-dermody can you take a look why this happens? It used to work fine before but I don't know if anything changed since.

**Comment by unsystemizer** [comment] 2017-09-18 15:00
I don't like to have these links broken so now I've made 2 changes (https://github.com/CounterpartyXCP/Documentation/commit/ae984ec3291babcb34cfd4d119308ebf459b4773) just to see if that helps. If it doesn't we can undo it, if it does, we can make more such fixes.

**Comment by unsystemizer** [comment] 2017-09-18 15:14
Hmm, it turns those were the only two links that were pointing to `/Developers/protocol_specification.md` and they've been changed and @jdogresorg confirmed it's OK now, so I'm closing this. 
For new/other stuff, please submit another issue.

**Closed by unsystemizer** 2017-09-18 15:14 UTC
